### PR TITLE
Custom Recipe

### LINKED ISSUE #49: Replicate DiceKeyWithDerivedSecret view

### LINKED ISSUE #88: Custom recipe not working
I can't enter a custom recipe ie website on samsung galaxy note 10. Everything else is working.

### PR DESCRIPTION
**Pull request by angelix**
Create and save custom recipes

Fix #88 
Fix #49

### CODE REVIEW

File: app/src/main/java/org/dicekeys/app/RecipeBuilder.kt [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+    fun updateDomains(domains: String){
+
+        // Check if is valid URL
+        try{
+            val url = URL(domains)
+            domainList = listOf(url.host)
+            return
+        }catch (e: Exception){
+            e.printStackTrace()
```
Comment (UppaJung) [inline app/src/main/java/org/dicekeys/app/RecipeBuilder.kt:29]: Was this just for debugging?

Comment (angelix) [reply app/src/main/java/org/dicekeys/app/RecipeBuilder.kt:29]: It's used only for the test, no need to reset it on the app because always we set the default values.

File: app/src/main/java/org/dicekeys/app/RecipeBuilder.kt [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+    fun getDerivationRecipe(): DerivationRecipe? {
+        if(template == null) {
+            val name = domainList.joinToString(", ")
+            val allowDomainList = domainList.map { """{"host":"*.$it"}""" }
+
+            if (domainList.isEmpty()) {
+                return null
+            }
+
+            val recipe = DerivationRecipe(DerivationOptions.Type.Password, name, """{"allow":[${allowDomainList.joinToString(",")}]}""")
```
Comment (UppaJung) [inline app/src/main/java/org/dicekeys/app/RecipeBuilder.kt:57]: The literal string code should probably be centralized somewhere since it's the part we need to be sure is common among all platforms.

**Review by UppaJung — APPROVED** [review]
