### PR TITLE
Fix: Cluttered home screen with multiple scanned keys

### LINKED ISSUE #86: Cluttered home screen with multiple scanned keys
When multiple keys are saved, the home screen gets cluttered to the point that text begins to disappear.

dicekeys-android

### PR DESCRIPTION
**Pull request by angelix**
Fix #86

### CODE REVIEW

File: app/src/main/java/org/dicekeys/app/views/DiceKeyCenterFaceOnlyView.kt [hunk 1]
```diff
@@ -184,8 +184,17 @@ class DiceKeyCenterFaceOnlyView @JvmOverloads constructor(
...
+        var width = MeasureSpec.getSize(widthMeasureSpec).toFloat()
+        var height = MeasureSpec.getSize(heightMeasureSpec).toFloat()
+
+        // Find the correct width/height that will respect the aspect ratio
+        val newHeight = width * ASPECT_RATIO
+
+        if(newHeight < height){
+            height = newHeight.toFloat()
+        }else{
+            width = (height / 1.5).toFloat()
```
Comment (UppaJung) [inline app/src/main/java/org/dicekeys/app/views/DiceKeyCenterFaceOnlyView.kt:196]: Why is this not 
```
width = height / ASPECT_RATIO
```
?

Comment (angelix) [reply app/src/main/java/org/dicekeys/app/views/DiceKeyCenterFaceOnlyView.kt]: Good catch, missed it when refactoring the code.

**Review by UppaJung — APPROVED** [review]
